



INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Finados', to_date ('2016-11-02', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Proclamação da República', to_date ('2016-11-15', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Natal', to_date ('2016-12-25', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Confraternização Universal', to_date ('2017-01-01', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Carnaval', to_date ('2017-02-28', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Paixão de Cristo', to_date ('2017-04-14', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Tiradentes', to_date ('2017-04-21', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Dia do trabalhador', to_date ('2017-05-01', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Corpus Christi', to_date ('2017-06-15', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Independência', to_date ('2017-09-07', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Revolução Farroupilha', to_date ('2017-09-20', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Nª. Sª. Aparecida ', to_date ('2017-10-12', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Finados ', to_date ('2017-11-02', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Proclamação da República ', to_date ('2017-11-15', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Natal ', to_date ('2017-12-25', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Confraternização Universal', to_date ('2018-01-01', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Carnaval', to_date ('2018-02-13', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Paixão de Cristo', to_date ('2018-04-14', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Tiradentes', to_date ('2018-04-21', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Dia do trabalhador', to_date ('2018-05-01', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Corpus Christi', to_date ('2018-06-15', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Independência', to_date ('2018-09-07', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Revolução Farroupilha', to_date ('2018-09-20', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Nª. Sª. Aparecida', to_date ('2018-10-12', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Finados', to_date ('2018-11-02', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Proclamação da República', to_date ('2018-11-15', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Natal', to_date ('2018-12-25', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Confraternização Universal', to_date ('2019-01-01', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Carnaval', to_date ('2019-02-19', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Paixão de Cristo', to_date ('2019-04-14', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Tiradentes', to_date ('2019-04-21', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Dia do trabalhador', to_date ('2019-05-01', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Corpus Christi', to_date ('2019-06-15', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Independência', to_date ('2019-09-07', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Revolução Farroupilha', to_date ('2019-09-20', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Nª. Sª. Aparecida', to_date ('2019-10-12', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Finados', to_date ('2019-11-02', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Proclamação da República', to_date ('2019-11-15', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Natal', to_date ('2019-12-25', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Confraternização Universal', to_date ('2020-01-01', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Carnaval', to_date ('2020-02-25', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Paixão de Cristo', to_date ('2020-04-14', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Tiradentes', to_date ('2020-04-21', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Dia do trabalhador', to_date ('2020-05-01', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Corpus Christi', to_date ('2020-06-15', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Independência', to_date ('2020-09-07', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Revolução Farroupilha', to_date ('2020-09-20', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Nª. Sª. Aparecida', to_date ('2020-10-12', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Finados', to_date ('2020-11-02', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Proclamação da República', to_date ('2020-11-15', 'YYYY-MM-DD'));

INSERT INTO T400FERI (DESC_FERIADO, DESC_DATA)
VALUES ('Natal', to_date ('2020-12-25', 'YYYY-MM-DD'));



